name: Flight Price Check

on:
  schedule:
    - cron: "0 * * * *" # Run hourly
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install
          ls -la
          cat package.json

      - name: Run price check
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        run: |
          echo "Running price check..."
          node fetch-check.js
          echo "Price check completed"
          ls -la

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git status
          git add price.json price-history.json || echo "No price files to add"
          git commit -m "Update flight prices" || echo "No changes to commit"
          git push || echo "No changes to push"
