name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./       # or 'docs/' if you put your site there

      - name: Deploy to GitHub Pages 🚀
        uses: actions/deploy-pages@v1
